SELECT T.FLAVOR
FROM (
SELECT J.FLAVOR, (SUM(J.TOTAL_ORDER) + SUM(FH.TOTAL_ORDER)) TOTAL_ORDER
FROM JULY J
LEFT OUTER JOIN FIRST_HALF FH
ON J.FLAVOR = FH.FLAVOR AND J.SHIPMENT_ID = FH.SHIPMENT_ID
GROUP BY J.FLAVOR
ORDER BY TOTAL_ORDER DESC
) T
LIMIT 3;

