SELECT 
    c.CAR_ID, 
    c.CAR_TYPE,
    FLOOR(
        c.DAILY_FEE * 30 * 
        (1 - IFNULL(dp.DISCOUNT_RATE / 100.0, 0))
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp 
    ON c.CAR_TYPE = dp.CAR_TYPE AND dp.DURATION_TYPE = '30일 이상'
LEFT JOIN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
) AS unavailable_cars 
    ON c.CAR_ID = unavailable_cars.CAR_ID
WHERE 
    c.CAR_TYPE IN ('세단', 'SUV') 
    AND unavailable_cars.CAR_ID IS NULL
HAVING 
    FEE >= 500000 AND FEE < 2000000
ORDER BY 
    FEE DESC, 
    c.CAR_TYPE ASC, 
    c.CAR_ID DESC;

