WITH REG_USER AS (
    SELECT COUNT(USER_ID) CNT_USER
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
    PURC_USER AS (
    SELECT COUNT(DISTINCT OS.USER_ID) CNT_USER,
        YEAR(OS.SALES_DATE) YEAR,
        MONTH(OS.SALES_DATE) MONTH
    FROM USER_INFO UI
    JOIN ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID
    WHERE YEAR(UI.JOINED) = 2021
    GROUP BY 2, 3
)
SELECT PU.YEAR, 
       PU.MONTH, 
       PU.CNT_USER PURCHASED_USERS, 
       ROUND(PU.CNT_USER/RU.CNT_USER, 1) PURCHASED_RATIO
FROM REG_USER RU, PURC_USER PU
ORDER BY 1, 2;

