SELECT CAR_ID,
    CASE
        WHEN EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY SUB
            WHERE SUB.CAR_ID = MAIN.CAR_ID
                AND '2022-10-16' BETWEEN SUB.START_DATE AND SUB.END_DATE
        ) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) MAIN
ORDER BY CAR_ID DESC;

