SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD UGB
    JOIN USED_GOODS_USER UGU
    ON UGB.WRITER_ID = UGU.USER_ID
    WHERE UGB.STATUS = 'DONE'
    GROUP BY 1, 2
    HAVING SUM(UGB.PRICE) >= 700000
    ORDER BY 3;

