-- LEFT JOIN 사용
SELECT AO.ANIMAL_ID, AO.NAME
    FROM ANIMAL_OUTS AO
    LEFT JOIN ANIMAL_INS AI
    ON AO.ANIMAL_ID = AI.ANIMAL_ID
    WHERE AI.ANIMAL_ID IS NULL
    ORDER BY 1, 2;

-- WHERE NOT EXISTS 사용
# SELECT ANIMAL_ID, NAME
#     FROM ANIMAL_OUTS AO
#     WHERE NOT EXISTS (
#     SELECT 1
#     FROM ANIMAL_INS AI
#     WHERE AI.ANIMAL_ID = AO.ANIMAL_ID)
#     ORDER BY 1, 2;

