WITH MAX_FISH AS (
    SELECT FISH_TYPE, MAX(LENGTH) LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT FI.ID, FNI.FISH_NAME, MF.LENGTH
FROM FISH_INFO FI
JOIN MAX_FISH MF
ON FI.FISH_TYPE = MF.FISH_TYPE AND FI.LENGTH = MF.LENGTH
JOIN FISH_NAME_INFO FNI
ON MF.FISH_TYPE = FNI.FISH_TYPE;

