WITH CTE AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY 1
)
SELECT RI.FOOD_TYPE, REST_ID, REST_NAME, RI.FAVORITES
    FROM REST_INFO RI
    JOIN CTE C
    ON RI.FOOD_TYPE = C.FOOD_TYPE AND RI.FAVORITES = C.FAVORITES
    ORDER BY 1 DESC;

