WITH MOST_VIEW AS (
    SELECT *
    FROM USED_GOODS_BOARD UGB
    ORDER BY UGB.VIEWS DESC
    LIMIT 1
)
SELECT CONCAT('/home/grep/src/', MV.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM MOST_VIEW MV
JOIN USED_GOODS_FILE UGF
ON MV.BOARD_ID = UGF.BOARD_ID
ORDER BY FILE_ID DESC;

